### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by yuyingz** [mistic100/Photo-Sphere-Viewer#1484]
### Describe the bug

I copied the demo of 'Equirectangular tiles' from the official website and debugged it on my Vue project, but encountered errors such as' three' and couldn't debug it. I don't know where the problem lies
![Weixin Image_20241113173800](https://github.com/user-attachments/assets/c2b6e2ab-6321-4395-8360-c8f04df428bf)

### Photo Sphere Viewer version

5.11.1

### OS & browser

chrome

**Comment by yuyingz** [comment]
This is an error

![Uploading Weixin Image_20241113173819.png…]()

**Comment by yuyingz** [comment]
This is an error

three.module.js:13465 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at updateBuffer (three.module.js:13465:1)
    at Object.update (three.module.js:13711:1)
    at Object.update (three.module.js:17559:1)
    at Object.update (three.module.js:18030:1)
    at projectObject (three.module.js:30006:1)
    at projectObject (three.module.js:30006:1)
    at projectObject (three.module.js:30006:1)
    at projectObject (three.module.js:30006:1)
    at WebGLRenderer.render (three.module.js:29880:1)
    at Renderer.__renderLoop (undefined***********************************************************:251:1)


![Uploading Weixin Image_20241113173819.png…]()

**Comment by mistic100** [comment]
I cannot help withot a demo. I don't know what is on line 13465 of three !!

**Comment by yuyingz** [comment]
I have found the reason for the error. It is because my 'three' version is 0.138.3 and needs to be updated to 0.170 for compatibility
