### ISSUE TITLE
videoPlugin destroy error

### ISSUE THREAD

**Issue by amipei** [mistic100/Photo-Sphere-Viewer#658]
## Issues guidelines

If use the video plugin, an error will be reported when the viewer is destroyed,

**Comment by mistic100** [comment]
Can you at least copy-paste the error here ? :roll_eyes:

**Comment by amipei** [comment]
> 您至少可以在此处复制粘贴错误吗？🙄

**Comment by amipei** [comment]
> 你可以在这里复制粘贴错误吗？🙄

I'm sorry。

`TypeError: Cannot read properties of undefined (reading 'off')
    at ProgressBar.destroy (ProgressBar.js:72:14)
    at VideoPlugin.destroy (index.js:126:23)
    at Viewer.js:310:41
    at misc.js:170:5
    at Array.forEach (<anonymous>)
    at each (misc.js:169:23)
    at Viewer.destroy (Viewer.js:310:5)
    at VideoPanoService.destroy (VideoPanoService.ts?f1b5:87:1)
    at eval (VideoPano.vue?acc4:57:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5722:155:1)`
